'use strict';
const $=id=>document.getElementById(id);let model;
const examples={kyc:'Your bank KYC expires today. Account blocked within 2 hours. Update Aadhaar at https://bank-kyc-check.example/verify and share your OTP immediately.',prize:'Congratulations! You won a FREE prize worth 10000! Claim your reward now. Pay a small processing fee at http://prize-claim.example.',family:'Hi, this is dad on my new number. Lost my phone. Please transfer money by UPI urgently, I cannot talk now.',normal:'Hi! Study group meets in the library at 4. Bring your notes and we can revise together.',unknown:'आपका संदेश जांचें'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('message').addEventListener('input',()=>$('count').textContent=$('message').value.length+' / 10,000');
for(const b of document.querySelectorAll('[data-example]'))b.addEventListener('click',()=>{$('message').value=examples[b.dataset.example];$('message').dispatchEvent(new Event('input'));check();});
$('clear').addEventListener('click',()=>{$('message').value='';$('message').dispatchEvent(new Event('input'));$('result').innerHTML='<div class="empty"><div class="lens">◎</div><h2>Message cleared.</h2><p>No messages are stored. Paste another when you need a second look.</p></div>';$('message').focus();});
$('analyze').addEventListener('click',check);
function check(){if(!model)return;try{
 const r=ScamLens.analyze($('message').value,model);let cls=r.level==='High caution'?'high':r.level==='Check independently'?'check':'';
 const desc=r.level==='High caution'?'Pause before clicking, paying or sharing a code. Verify through a known contact or the official app.':r.level==='Check independently'?'Some clues need a manual check. We cannot verify who sent this message.':'No strong warning signals appeared, but this is not a safety verdict. Verify any sensitive request.';
 $('result').innerHTML='<span class="status '+cls+'">'+r.level+'</span><h2>Your next move: verify.</h2><p class="muted">'+desc+'</p><div class="notice">'+r.warning+'</div><h3>Local ML: learned message patterns</h3>'+(r.supported?'<div class="score-row"><span>Uncalibrated model score</span><strong>'+Math.round(r.spamScore*100)+'%</strong></div><div class="bar"><span style="width:'+Math.round(r.spamScore*100)+'%"></span></div><p class="fine">'+(r.modelFlag?'Above':'Below')+' the 80% model flag threshold. Not a fraud probability.</p>':'<p class="muted">Model abstained: too short, non-ASCII or too little vocabulary overlap. Manual signals still shown. No misleading confidence score.</p>')+'<h3>Words pushing the score upward</h3><div class="chips">'+(r.supported&&r.contributors.length?r.contributors.map(x=>'<span>'+esc(x.token)+'</span>').join(''):'<span>No supported positive word evidence</span>')+'</div><h3>Warning signals (separate rules)</h3>'+(r.evidence.length?r.evidence.map(e=>'<div class="signal"><strong>'+esc(e.label)+'</strong><p>'+esc(e.explain)+'</p></div>').join(''):'<p class="muted">No listed warning patterns matched. New scams can still pass.</p>')+(r.links.length?'<h3>Link clues (not opened)</h3>'+r.links.map(l=>'<div class="link-info"><strong>Actual hostname: '+esc(l.host)+'</strong><br>'+esc(l.signals.join(' · ')||'No listed URL-pattern flags. HTTPS and a clean-looking name do not prove safety.')+'</div>').join(''):'')+'<h3>Safe next steps</h3><ol class="muted"><li>Do not click links or share codes while uncertain.</li><li>Open the official app yourself or call a number you already trust.</li><li>If you already paid or shared details, contact your bank through its official channel promptly.</li></ol>';
}catch(e){$('result').innerHTML='<p class="error">'+esc(e.message)+'</p>';}}
Promise.all([fetch('model.json').then(r=>{if(!r.ok)throw Error('Model load failed');return r.json()}),fetch('metrics.json').then(r=>r.json())]).then(([m,k])=>{model=m;$('analyze').disabled=false;$('analyze').textContent='Check message locally';$('metrics').innerHTML='<div class="metric-grid"><div><strong>'+k.test_count+'</strong>Held-out messages</div><div><strong>'+Math.round(k.precision*100)+'%</strong>Positive precision</div><div><strong>'+(k.recall*100).toFixed(1)+'%</strong>Spam/smishing recall</div><div><strong>'+k.false_negative+'</strong>Missed positives</div></div><p>'+k.train_count+' training messages; '+k.unique_messages+' unique English messages after deduplication. Template-group-disjoint 60/20/20 split, seeds 42/43; validation selected the 80% threshold. '+k.true_positive+' true positives, '+k.false_positive+' false positives, '+k.true_negative+' true negatives and '+k.false_negative+' false negatives.</p><p>'+esc(k.scope)+'</p>';}).catch(e=>{$('analyze').textContent='Model unavailable';$('result').innerHTML='<p class="error">Could not load the model. Serve this folder with Python rather than opening index.html directly.</p>';});
